# Generated by Django 3.0.1 on 2020-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200730_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/avatars/avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
