# Generated by Django 3.0.1 on 2020-07-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200731_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/avatars/avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
