# Generated by Django 3.0.1 on 2020-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_aboutyou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/profile/avatar.png', null=True, upload_to='profile'),
        ),
    ]
