# Generated by Django 3.0.1 on 2020-07-31 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200730_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/images/default-image.jpg', null=True, upload_to='images/'),
        ),
    ]
