# Generated by Django 3.0.1 on 2020-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imabge_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
