# Generated by Django 3.0.1 on 2020-08-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_imabge_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='imabge_by',
            new_name='image_by',
        ),
    ]
