# Generated by Django 3.0.1 on 2020-08-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.TextField(default='Jorge Luis Borges', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(default='I can give you my loneliness, my darkness, the hunger of my heart, I am trying to bribe you with uncertainty, with danger, with defeat'),
        ),
    ]
